### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by MH1405** [nlhans/MAS2Extract#3]
Hello, I am interested in using your program but unfortunately know nothing about programming and code like this so I dont understand how to use it. Could you give some quick instructions on how to use it? Thanks.

**Comment by whateverfloatsyourgoat** [comment]
I'll bump this because I don't know either and no one seems interested to help me.

**Comment by nlhans** [comment]
I'm sorry but this program code is on Github as-is. I can't provide programming tutorials.
